server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10

spring:
  datasource:
    name: localhost_3306
    url: jdbc:mysql://localhost:3306/wx_test_base?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    max-active: 30
    initial-size: 1
    max-wait: 60000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    password: 123456
    username: root
  application:
    name: micro-provider
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

