server:
  port: 9005

spring:
  application:
    name: my-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JimmyCW/mycloud/     # 配置git仓库的地址
          search-paths: tree/feature/20181004/repo-config                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: jimmywei19@163.com                                        # git仓库的账号
          password: 41689583wei                          # git仓库的密码
