server:
  port: 9002
spring:
  application:
    name: micro-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
feign:
  hystrix:
    enabled: true

